---
# golangci-lint configuration for Terraform Provider
# See https://golangci-lint.run/usage/configuration/ for all options

run:
  timeout: 5m
  tests: true
  # Define which Go version to target for linting
  go: '1.22'

output:
  # Format output
  formats:
    - format: colored-line-number
  # Print lines of code with issue
  print-issued-lines: true
  # Print linter name in the end of issue text
  print-linter-name: true
  # Sort results by file, line, and column
  sort-results: true

linters:
  enable:
    # Default linters
    - errcheck        # Check for unchecked errors
    - gosimple        # Simplify code
    - govet           # Vet examines Go source code
    - ineffassign     # Detect ineffectual assignments
    - staticcheck     # Go static analysis
    - unused          # Check for unused code

    # Additional recommended linters
    - gofmt           # Check if code was gofmt-ed
    - goimports       # Check import statements formatting
    - misspell        # Find commonly misspelled English words
    - revive          # Fast, configurable, extensible, flexible linter
    - gosec           # Inspect source code for security problems
    - unconvert       # Remove unnecessary type conversions
    - unparam         # Report unused function parameters
    - prealloc        # Find slice declarations that could be preallocated
    - nolintlint      # Report ill-formed or insufficient nolint directives
    - copyloopvar     # Check for loop variables captured by func literals (replaces exportloopref)
    - gocritic        # Comprehensive Go source code linter
    - gocyclo         # Compute cyclomatic complexity
    - bodyclose       # Check HTTP response body is closed
    - errorlint       # Find code that will cause problems with Go 1.13+ error wrapping

  disable:
    - typecheck       # Disabled because it can conflict with Go build

linters-settings:
  errcheck:
    # Report about not checking of errors in type assertions: `a := b.(MyStruct)`
    check-type-assertions: true
    # Report about assignment of errors to blank identifier: `num, _ := strconv.Atoi(numStr)`
    check-blank: false
    # Exclude functions - these are known to return errors we intentionally ignore
    exclude-functions:
      - '(*database/sql.DB).Close'
      - '(*database/sql.Rows).Close'

  gocyclo:
    # Minimal cyclomatic complexity to report
    min-complexity: 15

  govet:
    # Enable all analyzers
    enable-all: true
    # Disable specific analyzers
    disable:
      - shadow  # Can be too noisy

  misspell:
    locale: US
    ignore-words:
      - ovs
      - vsctl
      - ofctl
      - openvswitch

  gosec:
    # Exclude specific security checks
    excludes:
      - G204  # Subprocess launched with variable - we need this for ovs-vsctl commands
      - G304  # File path provided as taint input
    # Confidence level to report issues
    confidence: medium

  revive:
    rules:
      - name: exported
        disabled: false
        arguments:
          - "disableStutteringCheck"
      - name: package-comments
        disabled: true  # Not all packages need comments in small projects

  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - commentedOutCode
      - whyNoLint

  staticcheck:
    # https://staticcheck.io/docs/options#checks
    checks:
      - "all"
      - "-SA1019"  # Allow deprecated functions temporarily during migration

issues:
  # Maximum issues count per one linter
  max-issues-per-linter: 0
  # Maximum count of issues with the same text
  max-same-issues: 0

  # Show all issues from a linter
  new: false

  # Make issues output unique by line
  uniq-by-line: true

  # Exclude specific issues
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gosec
        - errcheck
        - gocritic

    # Exclude known issues in legacy code that will be fixed during SDK migration
    - path: openvswitch/
      text: "SA1019"  # Deprecated function usage (terraform v0.12 SDK)
      linters:
        - staticcheck

    # Allow complex functions in test files
    - path: _test\.go
      linters:
        - gocyclo

  # Independently of option `exclude` we use default exclude patterns
  exclude-use-default: true
