# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines bellow are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    binary: terraform-provider-openvswitch
    goos:
      - linux
      - windows
      - darwin

    goarch:
      - amd64
      - arm
      - arm64

    ignore:
      - goos: linux
        goarch: "386"
      - goos: linux
        goarch: arm
      - goos: windows
        goarch: arm

archives:
  - formats: zip
    # Terraform/OpenTofu provider install expects a zip.
    name_template: >-
      terraform-provider-openvswitch_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}amd64
      {{- else if eq .Arch "arm64" }}arm64
      {{- else if eq .Arch "arm" }}arm
      {{- else }}{{ .Arch }}{{ end }}

    files:
      - none*

    wrap_in_directory: false

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
