name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.18'
        cache: true

    - name: Build
      run: go build -v ./...

    - name: Format Check
      run: make fmtcheck

    - name: Test
      run: make test